spring:
  application:
    name: app-feign
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
    appname: app-feign
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



