spring:
  application:
    name: app-feign
  cloud:
    # 负载均衡器缓存
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
    appname: app-feign
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



