server:
  port: 8086

spring:
  application:
    name: app-hystrix-hystrix

  cloud:
    # 负载均衡器缓存
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s

eureka:
  instance:
    hostname: localhost
    appname: app-hystrix
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


feign:
  hystrix:
    enabled: true #开启客户端 hystrix

    ######################配置请求超时时间##########################
hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 5000
        ####################配置具体方法超时时间 为 3 秒########################
        HystrixRepository#queryUser(Map):
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 3000


