spring:
  application:
    name: app-provider
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    appname: app-provider
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/



