server:
  port: 8084

spring:
  application:
    name: app-hystrix

  cloud:
    # 负载均衡器缓存
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s

eureka:
  instance:
    hostname: localhost
    appname: app-hystrix
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

  #openfeign通过属性配置文件设置ribbon负载均衡策略
app-openfeign:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

  #曾强日志
logging:
  level:
    #openfeign 日志以什么样的级别监控该接口
    com.app.openfeign.repository.FeignRepository: debug




